### ISSUE TITLE
cannot reproduce your experimental results

### ISSUE THREAD

**Issue by tmsxk** [zhangzwwww/DietCodeBERT#2]
Sorry to bother you. The code you provided seems to be missing the file python_ statement.py, which makes it impossible for me to reproduce your experimental results of python dataset.

**Comment by 9erxis** [comment]
> Sorry to bother you. The code you provided seems to be missing the file python_ statement.py, which makes it impossible for me to reproduce your experimental results of python dataset.

I'm sorry to miss the file, i've uploaded it now.
