### ISSUE TITLE
how to get the file low_rated_word

### ISSUE THREAD

**Issue by tmsxk** [zhangzwwww/DietCodeBERT#3]
Thank you to upload the missing files, but when I want to reproduce your experimental results, there is an error that "FileNotFoundError: [Errno 2] No such file or directory: './low_rated_word'". I didn't find a way to get this file in README. I hope you can upload the file or tell me how to generate it through the code you provided. Thank you very much for your prompt reply

**Comment by 9erxis** [comment]
The file contains the 5,000 lowest attentioned tokens generated from CodeBERT. I have uploaded examples for both Java and Python in utils folder.

**Comment by tmsxk** [comment]
> The file contains the 5,000 lowest attentioned tokens generated from CodeBERT. I have uploaded examples for both Java and Python in utils folder.

Thanks for your timely reply. I found that a file named "token_frequency. py" seems to be missing in the downsteam task code2nl. Please upload it when you have free time.

**Comment by 9erxis** [comment]
> > The file contains the 5,000 lowest attentioned tokens generated from CodeBERT. I have uploaded examples for both Java and Python in utils folder.
> 
> Thanks for your timely reply. I found that a file named "token_frequency. py" seems to be missing in the downsteam task code2nl. Please upload it when you have free time.

Done!

**Comment by tmsxk** [comment]
> > > The file contains the 5,000 lowest attentioned tokens generated from CodeBERT. I have uploaded examples for both Java and Python in utils folder.
> > 
> > 
> > Thanks for your timely reply. I found that a file named "token_frequency. py" seems to be missing in the downsteam task code2nl. Please upload it when you have free time.
> 
> Done!

I'm sorry to bother you for many times. At present, I have reproduced the java results of code2nl. Could you please provide the reference version of the python_statement_classification_map, which will provide great convenience for me to reproduce python related results.
