### ISSUE TITLE
Could you provide a reference version of python_map.

### ISSUE THREAD

**Issue by tmsxk** [zhangzwwww/DietCodeBERT#4]
According to you README, I have obtained a reference version of java_map which is used in prune.py. Through it, I successfully achieved the comparative performace on the java code summarization task as in your paper. Now I want to experiment in python dataset, so I hope you can provide a reference version of python_map. I tried to generate it through the analyse.py mentioned in your README, but failed.

**Comment by 9erxis** [comment]
I've added the referenced statement scores in prune.py file.
