### ISSUE TITLE
Missing Files and the meaning of symbol Ġ

### ISSUE THREAD

**Issue by watreyoung** [zhangzwwww/DietCodeBERT#5]
I have read your paper. It is a good idea and has a wonderful performance. I am interested in your experiment. However, i have two questions about the code.
The first question is missing the token_attention and statement_attention. According to the paper, the two files should be decided by the attention from the layers of CodeBERT or CodeT5. But the attention files or the the scripts that can calculate the attention values both did not occur in all the files you gave.
The second question is that the symbol Ġ. i have downloaded the dataset from CodeSearchNet, but i have no idea what the symbol means. But when i try token_frequency, Ġ is useful to split the token.

Looking forward to your reply！

**Comment by 9erxis** [comment]
> I have read your paper. It is a good idea and has a wonderful performance. I am interested in your experiment. However, i have two questions about the code. The first question is missing the token_attention and statement_attention. According to the paper, the two files should be decided by the attention from the layers of CodeBERT or CodeT5. But the attention files or the the scripts that can calculate the attention values both did not occur in all the files you gave. The second question is that the symbol Ġ. i have downloaded the dataset from CodeSearchNet, but i have no idea what the symbol means. But when i try token_frequency, Ġ is useful to split the token.
> 
> Looking forward to your reply！

Thanks for your attention to our work.
For the first question, you can run the code search testing script with the ```--output_attention``` option.
For the second question, Ġ is the special token to represent the beginning sub-token of variable names. You can check the author's explanation in [https://openreview.net/forum?id=jLoC4ez43PZ&noteId=O-8pm3aJHqe](https://openreview.net/forum?id=jLoC4ez43PZ&noteId=O-8pm3aJHqe).

**Comment by watreyoung** [comment]
Thanks for your reply. I found the commented part of the code in run_classifier.py and got the attention, and I noticed that you have updated the new file that uncommented the output_attention. And if I want to get the attention of all layers, the 557 line in utils.py shoud be changed.
Thanks again.
